"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Header } from "@/components/layout/Header";
import { insightsApi, transactionsApi } from "@/lib/api";
import { HealthScoreWidget } from "@/components/dashboard/HealthScoreWidget";
import { CategoryPieChart } from "@/components/charts/CategoryPieChart";
import { MonthlyBarChart } from "@/components/charts/MonthlyBarChart";
import { formatCurrency, CATEGORY_ICONS } from "@/lib/utils";
import { AlertTriangle, Lightbulb, Trophy, Info, RefreshCw, Loader2, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const typeConfig = {
  warning: { icon: AlertTriangle, color: "text-amber-500", bg: "bg-amber-500/10", border: "border-amber-500/20" },
  suggestion: { icon: Lightbulb, color: "text-blue-500", bg: "bg-blue-500/10", border: "border-blue-500/20" },
  achievement: { icon: Trophy, color: "text-emerald-500", bg: "bg-emerald-500/10", border: "border-emerald-500/20" },
  info: { icon: Info, color: "text-violet-500", bg: "bg-violet-500/10", border: "border-violet-500/20" },
};

interface Insight {
  id: string;
  type: string;
  title: string;
  body: string;
  priority: string;
  is_read: boolean;
  is_dismissed: boolean;
  created_at: string;
}

export default function InsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [healthScore, setHealthScore] = useState(null);
  const [categories, setCategories] = useState([]);
  const [monthly, setMonthly] = useState([]);
  const [subscriptions, setSubscriptions] = useState<{ merchant: string; amount: number; interval: string }[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const now = new Date();

  useEffect(() => {
    const fetchAll = async () => {
      try {
        const [insRes, healthRes, catsRes, monthRes] = await Promise.all([
          insightsApi.list(),
          insightsApi.healthScore(),
          transactionsApi.categories({ month: now.getMonth() + 1, year: now.getFullYear() }),
          transactionsApi.monthlyComparison(6),
        ]);
        setInsights(insRes.data);
        setHealthScore(healthRes.data);
        setCategories(catsRes.data);
        setMonthly(monthRes.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchAll();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const generateInsights = async () => {
    setGenerating(true);
    try {
      const { data } = await insightsApi.generate();
      toast.success(`Generated ${data.insights_generated} new insights!`);
      const { data: insData } = await insightsApi.list();
      setInsights(insData);
    } catch {
      toast.error("Could not generate insights");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <Header title="AI Insights" subtitle="Personalized financial intelligence" />
      <div className="p-6 space-y-6">
        {/* Top row */}
        <div className="grid lg:grid-cols-3 gap-4">
          <HealthScoreWidget score={healthScore} loading={loading} />
          <div className="lg:col-span-2">
            <CategoryPieChart data={categories} loading={loading} />
          </div>
        </div>

        {/* Monthly chart */}
        <MonthlyBarChart data={monthly} loading={loading} />

        {/* Insights list */}
        <div className="rounded-2xl border border-border bg-card p-5">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="font-semibold">AI Insights ({insights.length})</h3>
              <p className="text-xs text-muted-foreground">Generated by your expense analysis</p>
            </div>
            <button
              onClick={generateInsights}
              disabled={generating}
              className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-violet-600 hover:bg-violet-500 text-white text-sm font-medium transition-colors disabled:opacity-50"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              {generating ? "Generating..." : "Refresh"}
            </button>
          </div>

          {loading ? (
            <div className="space-y-3">
              {[1, 2, 3].map((i) => <div key={i} className="h-20 bg-muted rounded-xl animate-pulse" />)}
            </div>
          ) : insights.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Lightbulb className="w-10 h-10 mx-auto mb-3 opacity-30" />
              <p className="font-medium mb-1">No insights yet</p>
              <p className="text-sm">Upload a bank statement and click Refresh to generate AI insights</p>
            </div>
          ) : (
            <div className="grid md:grid-cols-2 gap-3">
              {insights.map((insight) => {
                const config = typeConfig[insight.type as keyof typeof typeConfig] ?? typeConfig.info;
                const Icon = config.icon;
                return (
                  <motion.div
                    key={insight.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={cn("p-4 rounded-xl border", config.bg, config.border)}
                  >
                    <div className="flex items-start gap-3">
                      <div className={cn("w-8 h-8 rounded-lg flex items-center justify-center shrink-0", config.bg)}>
                        <Icon className={cn("w-4 h-4", config.color)} />
                      </div>
                      <div>
                        <p className="text-sm font-semibold">{insight.title}</p>
                        <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{insight.body}</p>
                        <span className={cn(
                          "inline-block text-xs px-2 py-0.5 rounded-full mt-2",
                          insight.priority === "high" ? "bg-rose-500/20 text-rose-400" :
                          insight.priority === "medium" ? "bg-amber-500/20 text-amber-400" : "bg-blue-500/20 text-blue-400"
                        )}>
                          {insight.priority} priority
                        </span>
                      </div>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
